In [1]:
import pandas as pd
import os

folder = 'data/'
vegetables = sorted([f.split('.')[0] for f in os.listdir(folder) if f.endswith('.csv')][:-1])

dataframes = {}

for vegetable in vegetables:
    dataframes[vegetable] = pd.read_csv(f'{folder}/{vegetable}.csv', index_col='Date', parse_dates=True)

In [2]:
dataframes['Tomato'].tail()

,Bandarawela,Dambulla,Kandy,Keppetipola,Meegoda,Norochchole,Nuwaraeliya,Peliyagoda,Thambuththegama,Veyangoda
Date,,,,,,,,,,
2023-12-25,115.0,125.00,139.29,240.0,330.00,255.00,240.0,160.0,181.11,115.00
2023-12-26,150.0,351.67,356.67,350.0,315.00,365.00,325.0,182.5,100.00,122.50
2023-12-27,155.0,105.00,231.67,125.0,160.00,421.67,250.0,165.0,121.67,135.00
2023-12-28,285.0,170.00,255.00,375.0,85.00,278.75,210.0,105.0,475.00,259.17
2023-12-29,155.0,216.67,271.67,110.0,256.67,225.00,165.0,270.0,525.00,139.00

In [3]:
for vegetable in vegetables:
    df = dataframes[vegetable]
    df = df[df.index < '2023-01-01']
    dataframes[vegetable] = df

In [4]:
for vegetable in vegetables:
    dataframes[vegetable].to_csv(f'{folder}/{vegetable}.csv')